name: cd

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
      
jobs:
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: shh into ec2 instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl restart docker
            sudo docker stop solor-system-api || true
            sudo docker rm solor-system-api || true
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/solor-system-api:latest
            sudo docker run -d --env-file .env -p 80:8000 --name solor-system-api ${{ secrets.DOCKERHUB_USERNAME }}/solor-system-api:latest